### ISSUE TITLE
关于flutter自动化测试

### ISSUE THREAD

**Issue by Jimmuy** [rp517045939/flutter_driver_test_demo#1]
你好，请问你知道flutter怎么进行自动化测试吗？

目前看到的示例都是类似于单元测试这种的，有没有针对于flutter的黑盒测试这种不需要开发人员进行编写测试代码的，本人android开发，对测试这边不太熟悉，目前需要协助测试来完成flutter的自动化测试，可以分享下相关经验吗？打扰啦

另外我按照demo写的driver测试，ide报错 No devices found. 但是 adb devices是有一个设备的，所以这个fluter driver命令一直没有跑起来，请问你知道是什么原因吗？谢谢

**Comment by rp517045939** [comment]
> 你好，请问你知道flutter怎么进行自动化测试吗？
> 
> 目前看到的示例都是针对单元测试这种的，有没有针对于flutter的黑盒测试这种不需要开发人员进行编写测试代码的，本人android开发，对测试这边不太熟悉，目前需要协助测试来完成flutter的自动化测试，可以分享下相关经验吗？打扰啦
> 
> 另外我按照demo写的driver测试，ide报错找不到设备。但是adb devices是有一个设备的，所以这个fluter driver命令一直没有跑起来，请问你知道是什么原因吗？谢谢

1.我们这边Flutter 的自动化主要是做某些特定模块和功能回归测试，因为我们的APP是Flutter和原生混合开发。
2.使用Flutter Driver 来进行UI层自动化测试的话是需要有一定的代码功底 至少能够读写Dart。如果单纯的黑盒测试，直接点点点就好啦。如果需要协助测试来做自动化，还是直接让测试人员学学Dart吧~
3.需要引入Flutter Driver组件哦 可以参考我写的 https://blog.csdn.net/rp517045939/article/details/107829741 或者截图给我看看哦

**Comment by Jimmuy** [comment]
> > 你好，请问你知道flutter怎么进行自动化测试吗？
> > 目前看到的示例都是针对单元测试这种的，有没有针对于flutter的黑盒测试这种不需要开发人员进行编写测试代码的，本人android开发，对测试这边不太熟悉，目前需要协助测试来完成flutter的自动化测试，可以分享下相关经验吗？打扰啦
> > 另外我按照demo写的driver测试，ide报错找不到设备。但是adb devices是有一个设备的，所以这个fluter driver命令一直没有跑起来，请问你知道是什么原因吗？谢谢
> 
> 1.我们这边Flutter 的自动化主要是做某些特定模块和功能回归测试，因为我们的APP是Flutter和原生混合开发。
> 2.使用Flutter Driver 来进行UI层自动化测试的话是需要有一定的代码功底 至少能够读写Dart。如果单纯的黑盒测试，直接点点点就好啦。如果需要协助测试来做自动化，还是直接让测试人员学学Dart吧~
> 3.需要引入Flutter Driver组件哦 可以参考我写的 https://blog.csdn.net/rp517045939/article/details/107829741 或者截图给我看看哦

是的，这两天深入了解了下flutter app test ,确实对于测试来说学习成本还是挺高的，后面的那个问题也几经解决了，谢谢啦
